[package]
name = "automerge_sedimentree"
version = "0.1.0"
description = "Automerge integration for Sedimentree"

categories = ["web-programming"]
keywords = ["automerge", "sedimentree"]
readme = "./README.md"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
automerge = { workspace = true }
sedimentree_core = { path = "../sedimentree_core", default-features = false }

[features]
default = []
std = ["sedimentree_core/std"]

[lints]
workspace = true
