[workspace]
resolver = "3"
members = [
  "build_info",
  "sedimentree_automerge",
  "sedimentree_automerge_wasm",
  "sedimentree_core",
  "subduction_cli",
  "subduction_core",
  "subduction_wasm",
  "subduction_websocket"
]

[workspace.package]
edition = "2024"
rust-version = "1.90"
license = "MIT OR Apache-2.0"
repository = "https://github.com/inkandswitch/subduction"
authors = [
  "Alex Good <alex@patternist.xyz>",
  "Brooklyn Zelenka <hello@brooklynzelenka.com>"
]

[workspace.dependencies]
automerge = "0.7.0"
arbitrary = "1.4"
async-channel = "2.5.0"
async-tungstenite = "0.31.0"
base58 = "0.2.0"
blake3 = "1.8"
bolero = "0.13.4"
dashmap = "6.1"
futures = "0.3.31"
futures-timer = "3.0"
futures-util = "0.3.31"
hex = "0.4.3"
js-sys = "0.3.81"
nonempty = "0.12.0"
num = "0.4.3"
rand = "0.9.2"
serde = "1.0"
testresult = "0.4.1"
thiserror = "2.0"
tokio = { version = "1.46", features = ["full"] }
tokio-test = "0.4.4"
tokio-util = "0.7.16"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.2", features = ["env-filter"] }
wasm-bindgen-futures = "0.4.53"
wasm-bindgen = "0.2.103"
wasm_refgen = { path = "../keyhive/wasm_refgen" }
# wasm_refgen = "0.1.2"
wasm-tracing = { git = "https://github.com/dsgallups/wasm-tracing.git", rev = "9288999e1fbbd315bfa0602488138d40b2a55299" }

