[package]
name = "sedimentree_core"
version = "0.1.0"
description = "Core data types for the Sedimentree protocol."

authors.workspace = true
categories = ["data-structures"]
edition.workspace = true
keywords = ["set-reconcilliation"]
license.workspace = true
readme = "./README.md"
repository.workspace = true
rust-version.workspace = true

[dependencies]
arbitrary = { workspace = true, optional = true, features = ["derive"] }
blake3 = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
num = { workspace = true }
serde = { workspace = true, optional = true, features = ["derive"]}
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
arbitrary = { workspace = true, optional = false, features = ["derive"] }
bolero = { workspace = true, features = ["arbitrary"] }
rand = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
default = []
arbitrary = ["dep:arbitrary"]
serde = ["dep:serde"]

[lints]
workspace = true
