[package]
name = "subduction_websocket"
version = "0.1.0"
description = "WebSocket implementation for Subduction"

categories = ["web-programming"]
keywords = ["websocket", "sync", "subduction"]
readme = "./README.md"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-channel = { workspace = true }
async-lock = { workspace = true }
async-tungstenite = { workspace = true }
blake3 = { workspace = true }
ciborium = { workspace = true }
futures = { workspace = true }
futures_kind = { workspace = true }
futures-timer = { workspace = true, optional = true }
futures-util = { workspace = true }
rand = { workspace = true }
sedimentree_core = { path = "../sedimentree_core", default-features = false, features = ["serde"] }
subduction_core = { path = "../subduction_core", default-features = false, features = ["serde"] }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true, features = ["time"] }
tokio-util = { workspace = true, optional = true }
tracing = { workspace = true }
tungstenite = { workspace = true }

[dev-dependencies]
anyhow = "1.0"
arbitrary = { workspace = true }
sedimentree_core = { path = "../sedimentree_core", features = ["arbitrary", "serde", "std"] }
testresult = { workspace = true }
tokio = { workspace = true }
tokio-test = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter", "std"] }

[features]
default = ["std"]
futures-timer = ["std", "dep:futures-timer"]
std = [
  "async-channel/std",
  "async-lock/std",
  "blake3/std",
  "ciborium/std",
  "futures/std",
  "futures-util/io",
  "futures-util/std",
  "rand/std",
  "sedimentree_core/std",
  "subduction_core/std",
  "serde/std",
  "thiserror/std",
  "tracing/std",
]
tokio = [
  "async-tungstenite/tokio-native-tls",
  "dep:tokio",
  "dep:tokio-util",
  "futures-timer",
  "std"
]
tokio-rustls = [
  "async-tungstenite/tokio-rustls-native-certs",
  "dep:tokio",
  "dep:tokio-util",
  "futures-timer",
  "std"
]
tokio_client = ["tokio"]
tokio_server = ["tokio"]
tokio_client_rustls = ["tokio-rustls"]
tokio_server_rustls = ["tokio-rustls"]

[lints]
workspace = true
