[package]
name = "subduction_websocket"
version = "0.3.1"
description = "WebSocket transport layer for the Subduction sync protocol"

categories = ["web-programming"]
keywords = ["websocket", "sync", "subduction"]
readme = "./README.md"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-channel = { workspace = true }
async-lock = { workspace = true }
async-tungstenite = { workspace = true }
blake3 = { workspace = true }
minicbor = { workspace = true }
futures = { workspace = true }
future_form = { workspace = true }
futures-timer = { workspace = true, optional = true }
futures-util = { workspace = true }
rand = { workspace = true }
sedimentree_core = { workspace = true }
subduction_core = { workspace = true }
subduction_crypto = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true, features = ["time"] }
tokio-util = { workspace = true, optional = true }
tracing = { workspace = true }
tungstenite = { workspace = true }

[dev-dependencies]
eyre = { workspace = true }
arbitrary = { workspace = true }
sedimentree_core = { workspace = true, features = ["arbitrary", "serde", "std"] }
subduction_core = { workspace = true, features = ["test_utils"] }
testresult = { workspace = true }
tokio = { workspace = true }
tokio-test = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter", "std"] }

[features]
default = ["std"]
futures-timer = ["std", "dep:futures-timer"]
std = [
  "async-channel/std",
  "async-lock/std",
  "blake3/std",
  "minicbor/std",
  "futures/std",
  "futures-util/io",
  "futures-util/std",
  "rand/std",
  "rand/std_rng",
  "sedimentree_core/std",
  "subduction_core/std",
  "thiserror/std",
  "tracing/std",
]
tokio_base = [
  "dep:tokio",
  "dep:tokio-util",
  "futures-timer",
  "std"
]
tokio_client_any = ["tokio_base"]
tokio_server_any = ["tokio_base"]
tokio_client = ["tokio_client_any", "async-tungstenite/tokio-native-tls"]
tokio_server = ["tokio_server_any", "async-tungstenite/tokio-native-tls"]
tokio_client_rustls = ["tokio_client_any", "async-tungstenite/tokio-rustls-native-certs"]
tokio_server_rustls = ["tokio_server_any", "async-tungstenite/tokio-rustls-native-certs"]

[lints]
workspace = true
