[package]
name = "subduction_cli"
version = "0.1.0"
description = "CLI tool for running Subduction with WebSockets"

categories = ["command-line-utilities", "web-programming"]
keywords = ["subduction"]
readme = "./README.md"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
ahash = "0.8"
anyhow = "1.0"
async-lock = { workspace = true }
async-tungstenite = { workspace = true }
axum = "0.8"
ciborium = { workspace = true }
clap = { version = "4.5", features = ["derive"] }
console-subscriber = "0.5.0"
futures = { workspace = true }
futures_kind = { workspace = true }
futures-util = { workspace = true }
hex = "0.4"
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
rand = "0.9.2"
serde = { workspace = true }
sedimentree_core = { path = "../sedimentree_core", features = ["std", "serde"] }
subduction_core = { path = "../subduction_core", features = ["std", "serde-std", "metrics"] }
subduction_websocket = { path = "../subduction_websocket", default-features = false }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full", "tracing"] }
tokio-util = { workspace = true }
tracing = { workspace = true, default-features = true }
tracing-subscriber = { workspace = true, default-features = true }
tungstenite = { workspace = true }
url = { workspace = true, features = ["std"] }

[features]
default = ["native-tls"]
native-tls = [
  "async-tungstenite/tokio-native-tls",
  "subduction_websocket/tokio_client",
  "subduction_websocket/tokio_server",
]
rustls = [
  "async-tungstenite/tokio-rustls-native-certs",
  "subduction_websocket/tokio_client_rustls",
  "subduction_websocket/tokio_server_rustls",
]

[lints]
workspace = true
