name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  quality-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Build workspace
      run: cargo build --workspace --verbose

    - name: Build workspace with all features
      run: cargo build --workspace --verbose --all-features

    - name: Check workspace
      run: cargo check --workspace --verbose --all-features

    - name: Install Nightly Toolchain
      run: rustup toolchain install nightly --component rustfmt

    - name: Formatting
      run: cargo +nightly fmt --all -- --check

    - name: Clippy
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings
